## ch01. 신경망 복습
##### 밑시딥1 내용 복습
---
### 1.1 수학과 신경망 복습
#### 1.1.1 벡터와 행렬
- 벡터: 크기와 방향을 가진 양 -> 파이썬에는 1차원 배열로 취급
  + 행벡터(가로), 열벡터(세로)
- 행렬: 숫자가 2차원 형태로 늘어선 것 -> 2차원 배열로


In [3]:
import numpy as np

x = np.array([1, 2, 3])
print(x.__class__)
print(x.shape)
print(x.ndim)

W = np.array([[1, 2, 3], [4, 5, 6]])
print(W.shape)
print(W.ndim)

<class 'numpy.ndarray'>
(3,)
1
(2, 3)
2


#### 1.1.2 행렬의 원소별 연산
: 다차원 배열들에서 서로 대응하는 원소끼리 연산이 이루어짐.


In [4]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
print(W + X)
print(W * X)

[[ 1  3  5]
 [ 7  9 11]]
[[ 0  2  6]
 [12 20 30]]


#### 1.1.3 브로드캐스트
: `넘파이`의 다차원 배열에서는 형상이 다른 배열끼리도 연산 가능

In [6]:
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [8]:
A = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])